### ISSUE TITLE
"Update Library" button not available on Blender 4.0

### ISSUE THREAD

**Issue by AnimaMachina** [DeBullVader/BU_Blender_AssetLibrary_Plugin#8]
Seems the "Update Library" button available on Assets Browser is not available on Blender 4.0 (my old install blend 3.6.5 display it correctly). So if it's a news install on Blender 4.0, the asset library is empty and can't be downloaded.

**Comment by DeBullVader** [comment]
Yes it's currently not updated to 4.0 yet. We will release our new update next week. After that we will start updating everything to support 4.0 

All functions need to be checked because 4.0 has many breaking changes to the blender api. 

The next update has lots of improvements and will include access to our premium library and licensing. 

We will then focus on the 4.0 upgrade and will release a closed beta let users test the 4.0 version including geonodes that are made in 4.0
